apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
  namespace: envoy-gateway-system
spec:
  gatewayClassName: eg
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: proxy
  addresses:
    - type: IPAddress
      value: 130.246.83.9
  listeners:
  - name: argo-cd-http
    port: 80
    protocol: HTTP
    hostname: argo.secrets.isis.cclrc.ac.uk
    allowedRoutes:
      namespaces:
        from: All
  - name: argo-cd-https
    port: 443
    protocol: HTTPS
    hostname: argo.secrets.isis.cclrc.ac.uk
    allowedRoutes:
      namespaces:
        from: All
    tls:
      certificateRefs:
        - group: ""
          kind: Secret
          name: argo-self-signed-cert
  - name: vault-http
    port: 80
    protocol: HTTP
    hostname: secrets.isis.cclrc.ac.uk
    allowedRoutes:
      namespaces:
        from: All