apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
  namespace: envoy-gateway-system
spec:
  gatewayClassName: eg
  addresses:
    value: "130.246.83.9"
  listeners:
  - name: argocd-http
    port: 80
    protocol: HTTP
    hostname: argo.secrets.isis.cclrc.ac.uk